=== YannisNaidja/XMLTD/TD1/dtd1-2.dtd
<!--!DOCTYPE batiment [-->
<!ELEMENT batiment (etage)+ >
<!ELEMENT etage (description,(bureau+|salle+)) >

<!ELEMENT description (#PCDATA) >

<!ELEMENT bureau (code, personne*) >

<!ELEMENT code (#PCDATA) >

<!ELEMENT personne (#PCDATA) >

<!ELEMENT salle (nombrePlaces) >

<!ELEMENT nombrePlaces (#PCDATA) >

<!--	  ]>-->

=== YannisNaidja/XMLTD/TD3/rapport/batiment.xml
<!DOCTYPE batiment SYSTEM "dtd1-2.dtd">
<batiment>
  <etage>
     <description>
       descriptionEtage1
     </description>
     <salle>
       <nombrePlaces>
 	 25
       </nombrePlaces>
     </salle>
     <salle>
       <nombrePlaces>
 	50
       </nombrePlaces>
     </salle>
   </etage>
   <etage>
     <description>
       descriptionEtage2
     </description>
     <bureau>
       <code>
 	B02
       </code>
       <personne>
 	Personne1
       </personne>
     </bureau>
     <bureau>
       <code>
 	 B03
       </code>
       <personne>
 	Personne2
       </personne>
       <personne>
 	Personne3
       </personne>
     </bureau>
   </etage>
</batiment>
